apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes: 
        - name: html-volume
          configMap:
            name: frontend-cm
      containers:
        - name: nginx-frontend
          image: nginx
          env: 
            - name: APP
              valueFrom:
                configMapKeyRef:
                  name: frontend-cm # Added the CM name here!
                  key: APP
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: frontend-cm # Added the CM name here!
                  key: ENVIRONMENT
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80   
      nodePort: 31000