apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  volumes: 
  - name: persistent-storage
    persistentVolumeClaim: 
      claimName: example-pvc
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - mountPath:  /usr/share/nginx/html
      name: persistent-storage
